spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-round-shape-aon49yof-pooler.c-2.ap-southeast-1.aws.neon.tech/service_portal?sslmode=require&channelBinding=require}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_f0EQuULXsY9y}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jpa.open-in-view=false
server.port=8080
jwt.secret=${JWT_SECRET:eservice1-secret-key-eservice1-secret-key-123456}

file.max-size=30971520

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG

supabase.url=https://ddukimesjrqficgablww.supabase.co
supabase.bucket=documents
supabase.service-key=sb_secret_VL28QhuVqiWFeAYKf0WeNg_54HYgfvK

msg91.base-url=https://control.msg91.com/api/v5/flow
msg91.auth-key=${MSG91_AUTH_KEY}
msg91.template-id=6a74926fce1151bd780b7072
msg91.sender-id=NLIESE
msg91.otp-variable=number