spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-dawn-base-aoc9pj4c.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_5kG4MXFPJqQg}

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jpa.open-in-view=false
server.port=8080
jwt.secret=${JWT_SECRET:eservice1-secret-key-eservice1-secret-key-123456}

file.upload-dir=uploads
file.max-size=20971520