-- =========================================================================
-- V1__initial_schema.sql
-- Baseline schema for eservice1 application
-- Includes security constraints from Phases 1-4:
--   - Single OWNER unique partial index (uk_users_single_owner)
--   - CustomerRequest optimistic locking version (customer_requests.version)
--   - Payment audit trail table and index (payment_audit_logs, idx_pal_request_id)
--   - Feedback per request uniqueness (uk_feedback_request_id)
--   - Role, Status, and Purpose CHECK constraints
--   - Unique and foreign key integrity constraints
-- =========================================================================

-- Optional cryptographic extension
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Services
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    description VARCHAR(255),
    service_name VARCHAR(255)
);

-- 2. Service Categories
CREATE TABLE IF NOT EXISTS service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_service_categories_name UNIQUE (name)
);

-- 3. Category Services (ElementCollection)
CREATE TABLE IF NOT EXISTS category_services (
    category_id BIGINT NOT NULL,
    service_id BIGINT,
    CONSTRAINT fk_category_services_category FOREIGN KEY (category_id) REFERENCES service_categories (id)
);

-- 4. Customer Form Fields
CREATE TABLE IF NOT EXISTS customer_form_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    field_name VARCHAR(255),
    field_type VARCHAR(255),
    required_field BOOLEAN
);

-- 5. Customer Form Responses
CREATE TABLE IF NOT EXISTS customer_form_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(255),
    value VARCHAR(2000),
    field_id BIGINT,
    CONSTRAINT fk_customer_form_responses_field FOREIGN KEY (field_id) REFERENCES customer_form_fields (id)
);

-- 6. Customer Profiles
CREATE TABLE IF NOT EXISTS customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255),
    dob VARCHAR(255),
    phone_number VARCHAR(255) NOT NULL,
    CONSTRAINT uk_customer_profiles_phone_number UNIQUE (phone_number)
);

-- 7. Employees
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    address TEXT,
    dob DATE,
    email VARCHAR(255),
    gender VARCHAR(255),
    joined_date DATE,
    name VARCHAR(255),
    password VARCHAR(255),
    phone_number VARCHAR(255),
    profile_image VARCHAR(255),
    username VARCHAR(255)
);

-- 8. Customer Requests
CREATE TABLE IF NOT EXISTS customer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    customer_name VARCHAR(255),
    payment_date TIMESTAMP(6) WITHOUT TIME ZONE,
    payment_status VARCHAR(255),
    phone_number VARCHAR(255),
    status VARCHAR(255),
    service_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT customer_requests_payment_status_check CHECK (payment_status IS NULL OR payment_status IN ('UNPAID', 'PAID')),
    CONSTRAINT customer_requests_status_check CHECK (status IS NULL OR status IN ('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT fk_customer_requests_service FOREIGN KEY (service_id) REFERENCES services (id)
);

-- 9. Tasks
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority VARCHAR(255),
    status VARCHAR(255),
    employee_id BIGINT,
    request_id BIGINT,
    CONSTRAINT uk_tasks_request_id UNIQUE (request_id),
    CONSTRAINT tasks_priority_check CHECK (priority IS NULL OR priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT tasks_status_check CHECK (status IS NULL OR status IN ('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT fk_tasks_request FOREIGN KEY (request_id) REFERENCES customer_requests (id),
    CONSTRAINT fk_tasks_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

-- 10. Receipts
CREATE TABLE IF NOT EXISTS receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255),
    file_path VARCHAR(255),
    task_id BIGINT,
    CONSTRAINT uk_receipts_task_id UNIQUE (task_id),
    CONSTRAINT fk_receipts_task FOREIGN KEY (task_id) REFERENCES tasks (id)
);

-- 11. Required Documents
CREATE TABLE IF NOT EXISTS required_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name VARCHAR(255),
    mandatory BOOLEAN,
    service_id BIGINT,
    CONSTRAINT fk_required_documents_service FOREIGN KEY (service_id) REFERENCES services (id)
);

-- 12. Service Form Fields
CREATE TABLE IF NOT EXISTS service_form_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    field_name VARCHAR(255),
    field_type VARCHAR(255),
    required_field BOOLEAN,
    service_id BIGINT
);

-- 13. Service Form Responses
CREATE TABLE IF NOT EXISTS service_form_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT,
    request_id BIGINT,
    value VARCHAR(255)
);

-- 14. Feedback
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment VARCHAR(1000),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    customer_phone VARCHAR(255),
    rating INTEGER,
    request_id BIGINT,
    service_id BIGINT,
    CONSTRAINT uk_feedback_request_id UNIQUE (request_id),
    CONSTRAINT fk_feedback_request FOREIGN KEY (request_id) REFERENCES customer_requests (id),
    CONSTRAINT fk_feedback_service FOREIGN KEY (service_id) REFERENCES services (id)
);

-- 15. Login Attempts
CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    failed_attempts INTEGER NOT NULL,
    lock_until TIMESTAMP(6) WITHOUT TIME ZONE,
    phone_number VARCHAR(255),
    CONSTRAINT uk_login_attempts_phone_number UNIQUE (phone_number)
);

-- 16. OTP Verification
CREATE TABLE IF NOT EXISTS otp_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempts INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    otp VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    verified BOOLEAN NOT NULL,
    CONSTRAINT otp_verification_purpose_check CHECK (purpose IN ('CUSTOMER_LOGIN', 'EMPLOYEE_PASSWORD_RESET'))
);

-- 17. Payment Audit Logs
CREATE TABLE IF NOT EXISTS payment_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    previous_status VARCHAR(20) NOT NULL,
    new_status VARCHAR(20) NOT NULL,
    amount DOUBLE PRECISION,
    performed_by VARCHAR(255) NOT NULL,
    performed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    notes VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_pal_request_id ON payment_audit_logs (request_id);

-- 18. Uploaded Documents
CREATE TABLE IF NOT EXISTS uploaded_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name VARCHAR(255),
    file_name VARCHAR(255),
    file_path VARCHAR(255),
    result_document BOOLEAN,
    uploaded_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    request_id BIGINT,
    CONSTRAINT fk_uploaded_documents_request FOREIGN KEY (request_id) REFERENCES customer_requests (id)
);

-- 19. Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    password VARCHAR(255),
    phone_number VARCHAR(255),
    role VARCHAR(255),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT users_role_check CHECK (role IS NULL OR role IN ('CUSTOMER', 'EMPLOYEE', 'OWNER'))
);

-- Partial unique index ensuring at most one OWNER exists in the system
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_single_owner ON users (role) WHERE (role = 'OWNER');
