CREATE TABLE IF NOT EXISTS payment_audit_logs (
                                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  request_id BIGINT NOT NULL,
                                                  previous_status VARCHAR(255) NOT NULL,
    new_status VARCHAR(255) NOT NULL,
    amount DOUBLE PRECISION,
    performed_by VARCHAR(255) NOT NULL,
    performed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    notes VARCHAR(255)
    );